//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RegionsCSV {
            get {
                object obj = ResourceManager.GetObject("RegionsCSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap slovensko_map {
            get {
                object obj = ResourceManager.GetObject("slovensko_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap slovensko_mask {
            get {
                object obj = ResourceManager.GetObject("slovensko_mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bratislavský kraj;86;116;185
        ///Trnavský kraj;57;181;74
        ///Nitriansky kraj;237;0;140
        ///Trenčiansky kraj;0;74;128
        ///Žilinský kraj;96;57;19
        ///Banskobystrický kraj;247;151;121
        ///Prešovský kraj;255;248;153
        ///Košický kraj;238;28;36.
        /// </summary>
        internal static string slovensko_regions {
            get {
                return ResourceManager.GetString("slovensko_regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myjava;237;28;36
        ///Dunaj;0;84;166
        ///Váh;0;191;243
        ///Malý dunaj;89;133;39
        ///Nitra;0;94;32
        ///Hron;96;92;168
        ///Kysuca;255;0;255
        ///Orava;96;57;19
        ///Turiec;50;0;75
        ///Ipeľ;199;178;153
        ///Rimava;237;20;91
        ///Slaná;115;99;87
        ///Hornád;255;242;0
        ///Poprad;133;96;168
        ///Torysa;121;0;0
        ///Topľa;0;255;0
        ///Ondava;171;160;0
        ///Laborec;163;98;10
        ///Uh;123;46;0
        ///Latorica;0;255;255
        ///Bodrog;251;175;93.
        /// </summary>
        internal static string slovensko_rivers {
            get {
                return ResourceManager.GetString("slovensko_rivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sr_rieky_map {
            get {
                object obj = ResourceManager.GetObject("sr_rieky_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sr_rieky_mask {
            get {
                object obj = ResourceManager.GetObject("sr_rieky_mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
